config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'games#index', as: :games

  get 'pilfer/:location' => 'games#pilfer', as: :pilfer

  get 'reset' => 'games#reset', as: :reset

  root 'games#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :location, inclusion: { in: %w(Farm Cave House Casino), message: '%(value) is not a valid location.' }, presence: true
  validates :gold, numericality: true, presence: true

  def self.reset
    self.all.delete_all
  end

end

app/models/option.rb
class Option < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    session[:gold] ||= 0
    @options = Option.all
    @activities = Activity.all.limit(10).order('created_at desc')
  end

  def pilfer
    choice = Option.where(location:"#{params[:location]}").first
    if (choice[:gold_min] < 0) && (session[:gold] < choice[:gold_max])
      flash[:error] = "Only have #{session[:gold]} available, need at least #{choice[:gold_max]} gold to enter the casino."
    else
      gold = rand(choice[:gold_min]..choice[:gold_max])
      activity = Activity.create(location: choice[:location], gold: gold)
      session[:gold] += gold
    end
    redirect_to games_path
  end

  def reset
    session[:gold] = nil
    Activity.reset
    redirect_to games_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/activities/_activity.html.erb
<% if (activity.gold > 0) %>
  <p class="earn">Earned <%= activity[:gold] %> gold from the <%= activity[:location] %>! (<%= activity[:created_at].strftime('%Y/%m/%d %H:%M %a') %>)</p>
<% else %>
  <p class="lose">Entered <%= activity[:location] %> and lost <%= activity[:gold].abs %> gold..... Ouch. (<%= activity[:created_at].strftime('%Y/%m/%d %H:%M %a') %>)</p>
<% end %>

app/views/games/index.html.erb
<h1>Your Gold: <span id="gold"><%= session[:gold] %></span></h1>
<% if flash[:error] %>
  <h3 class="lose"><%= flash[:error] %></h3>
<% end %>
<div class="wrapper">
  <%= render @options %>
</div>
<h3>Activities:</h3>
<div class="wrapper">
  <div id="activity_log">
    <div id="log">
      <%= render @activities %>
    </div>
  </div>
</div>
<%= link_to "RESET", reset_path %>

app/views/games/process.html.erb
<h1>Games#process</h1>
<p>Find me in app/views/games/process.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninja Money</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/_option.html.erb
<div class="location">
  <h1><%= option[:location] %></h1>
  <% if(option[:gold_min] < 0) %>
    <p>(earns/loses 0-<%= option[:gold_max] %> gold))</p>
  <% else %>
    <p>(earns <%= option[:gold_min] %>-<%= option[:gold_max] %> gold)</p>
  <% end %>
  <%= link_to 'Find Gold!', pilfer_path(option[:location]) %>
</div>